### ISSUE TITLE
Project Structure and Release Management

### ISSUE THREAD

**Issue by M3ssman** [goobi/goobi-ugh#90]
Hello,

is it possible to merge the current 2.x Branch into Master? There is no `kitodo-ugh`contained in next `kitodo-production`Major-Version, so Kitodo 2.x is the only place to be for this library.
It is quite confusing when building a custom Version that Branch 2.x is so far in the future and diverged from the Master Branch.

Greetings,
M3ssman

**Comment by matthias-ronge** [comment]
I do not think it is the best solution to hard-erase the `master` branch. It would mean that the source code status including the change history would be irretrievably lost. The [Git garbage collection](https://git-memo.readthedocs.io/en/latest/garbage_collecting.html) would do its part. My suggestion would be to rename the `master` branch in `kitodo-3.0.0-beta.2` instead, which was the last version of Production that used the UGH. In addition, the `2.x` branch could be made the default branch of the repository.

**Comment by matthias-ronge** [comment]
Branch `2.x` should not be merged into the `master` branch. The `master` branch contains changes which were made specifically in the further development of Production version 3. The result would not be usable with Kitodo.Production 2.x. You are watching correctly that there is no UGH integration in the current Production version anymore. Changes to this repository relate to measures to legacy 2.x. My suggestion would be to rename the `master` branch in `kitodo-3.0.0-beta.2` instead, which was the last version of Production that used the UGH. In addition, the `2.x` branch could be made the default branch of the repository.

**Comment by M3ssman** [comment]
@matthias-ronge Thanks for explaning why these Branches are in diverged state.

Re-arranging Branch-Layout is a useful approach for sure.

Please note, that the main concern for this issue is the new `kitodo-production` Release 2.3, which contains `kitodo-ugh` latest build as Version 2.1.3. Unfortunately, this build is based on the `kitodo-ugh` Master-Branch and **_not_** on the 2.x-Branch that contains your Fix for #85 . Therefore we cannot use either the last build from `kitodo-ugh` nor `kitodo-production`, since it doesn't include your Patch and need to build the lib ourselves depending on `kitodo-ugh`2.x.

**Comment by M3ssman** [comment]
obsolete
